version: 0.2

phases:
  install:
    commands:
      - npm install # Install dependencies using npm

  pre_build:
    commands:
      - npm run build # Execute any pre-build tasks (e.g., transpilation, linting)

  build:
    commands:
      - webpack # Run webpack to bundle your JavaScript code

artifacts:
  files:
    - '**/*' # Include all files in the build output directory
 # base-directory: 'dist' # Specify the directory where built artifacts are located
